DROP TABLE "TIENDA".DETALLE_ORDEN;
DROP TABLE "TIENDA".ORDEN;
DROP TABLE "TIENDA".CLIENTE;
DROP TABLE "TIENDA".PRODUCTO;


create table "TIENDA".CLIENTE
(
	ID INTEGER  not null primary key
        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOMBRES VARCHAR(50),
	APELLIDOS VARCHAR(50)
);

create table "TIENDA".PRODUCTO
(
	ID INTEGER not null primary key
        GENERATED ALWAYS AS IDENTITY 
        (START WITH 1, INCREMENT BY 1),
	NOMBRE VARCHAR(50),
	DESCRIPCION VARCHAR(100),
	PRECIO DECIMAL(10)
);


create table "TIENDA".ORDEN
(
    ID INTEGER NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY 
    (START WITH 1, INCREMENT BY 1),
    ID_CLIENTE INTEGER not null REFERENCES CLIENTE(ID),
    FECHA DATE not null	
);

CREATE TABLE "TIENDA".DETALLE_ORDEN
(
    ID_ORDEN INTEGER NOT NULL REFERENCES ORDEN(ID),
    ID_PRODUCTO INTEGER not null REFERENCES PRODUCTO(ID),    
    CANTIDAD INTEGER not null,
    primary key (ID_ORDEN, ID_PRODUCTO)        
);